# Generated by Django 6.0.7 on 2026-07-20 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedartifact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('waiting', 'Waiting For Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=30),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workflow_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='error_message',
            field=models.TextField(blank=True, help_text='Stores AI execution errors for retry purposes.'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='feedback',
            field=models.TextField(blank=True, help_text='User feedback when requesting changes.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting Approval'), ('approved', 'Approved'), ('needs_changes', 'Needs Changes'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting_approval', 'Waiting Approval'), ('approved', 'Approved'), ('needs_changes', 'Needs Changes'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['project', 'status'], name='projects_wo_project_f44881_idx'),
        ),
    ]
